### ISSUE TITLE
Context Menu(right click) not working

### ISSUE THREAD

**Issue by dVIAN13** [yannhodiesne/Discord-M1#18]
Hello, I have noticed that the context menu in the text fields is not working.

For Example, mis-spell a word and try and right-click. In the native app, there is a right click context menu with spellcheck amongst other options. In a browser, the context menu is a standard right click menu, and includes spell check.

**Comment by yannhodiesne** [comment]
Fixed in https://github.com/yannhodiesne/Discord-M1/commit/c7e8bb0d5a865d1979107cd08c8d1216bb7dab89, text inputs now supports the native macOS context menu
Unfortunately, even after enabling spell checking, it did not seem to work on my side
I'm gonna release it with version 1.7.0 later today; if spellchecking does not work we will treat it as a separate issue
