### ISSUE TITLE
github opening each time application opens

### ISSUE THREAD

**Issue by valkyrie743** [yannhodiesne/Discord-M1#27]
everytime i open the app. it will open a web page to the github. can an option to disable this or a different pop up to check app version without having it open a web page each time

**Comment by yannhodiesne** [comment]
I imagine you closed this issue because you figured it out yourself

The old builds could not auto-update and opened the Releases pages when it detected a new version
The new builds are not as dumb and ask you if you want to update or not, without opening a browser page at all
You can install the latest version here: https://github.com/yannhodiesne/Discord-M1/releases
